services:
  app:
    build: .
    container_name: ai-engineer-app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://agent:agentpass@postgres:5432/ai_engineer
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:17
    container_name: ai-engineer-postgres
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_DB: ai_engineer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: